#!/usr/bin/env bash
# Script to install and configure HAproxy to send traffic between two servers and distribute requests using roundrobin
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get update
apt-get install -y haproxy=2.6.\*
ufw allow 1344
sed -i "35a\\nfrontend web_server\n\tbind *:80\n\tdefault_backend web_server\n" /etc/haproxy/haproxy.cfg
sed -i "40a\backend web_server\n\tbalance roundrobin\n\tserver 11359-web-01 3.236.55.133:80 check\n\tserver 11359-web-02 44.192.95.89:80 check" /etc/haproxy/haproxy.cfg
service haproxy restart